# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainReasonToBelieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст под заголовком')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=200, verbose_name='Назыание страницы')),
                ('project_name', models.CharField(default='My Landing Page', max_length=40, verbose_name='Название проекта')),
                ('phone', models.CharField(default='+7 000 000-00-00', max_length=20, verbose_name='Телефон')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_btn', models.CharField(default='Действие', max_length=50, verbose_name='Текст кнопки')),
                ('title_btn_url', models.CharField(blank=True, max_length=50, null=True, verbose_name='URL кнопки')),
                ('background_color', models.CharField(blank=True, default='#5180a5', max_length=7, null=True, verbose_name='Цвет фона')),
                ('footer_content', models.TextField(blank=True, null=True, verbose_name='Подвал')),
            ],
            options={
                'verbose_name_plural': 'Страницы проекта',
                'verbose_name': 'Страница проекта',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('sub_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Подзаголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Блок')),
                ('img_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на изображение')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Page')),
            ],
            options={
                'verbose_name_plural': 'Процесс',
                'verbose_name': 'Процесс',
            },
        ),
        migrations.AddField(
            model_name='mainreasontobelieve',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Page'),
        ),
    ]
